# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          ./assets/styles
  style:            :compressed

exclude: 
  - node_modules
  - LICENSE
  - Makefile
  - README.md
  - package.json
  - package-lock.json
  - yarn.lock
